name: Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-pages:
    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write
      packages: read
    uses: moritzbrantner/reusable-workflows/.github/workflows/deploy-pages.yml@workflow-standard-v1.3
    with:
      node_version: ""
      bun_version: ""
      install_command: ""
      build_command: ""
      artifact_path: site
      cache_bun: false
      cache_node: false
      concurrency_group: shader-lab-pages
      cancel_in_progress: false
